batch_size: 64
buffer_size: 2048
clip_ratio: 0.2
context_size: 5
counterfactual_coef: 0.1
counterfactual_horizon: 5
curriculum_min_episodes: 100
curriculum_success_threshold: 0.7
curriculum_type: grid
curriculum_update_freq: 10
curriculum_window_size: 100
dataset: combined
device: cuda
distance_coef: 0.1
distance_threshold: 1.0
encoding_size: 256
entropy_coef: 0.01
eval_episodes: 20
eval_goal_prob: 1.0
gamma: 0.99
goal_prob: 0.5
grid_size: 5
hidden_dim: 512
image_size:
- 224
- 224
lam: 0.95
learning_rate: 0.0003
log_freq: 10
max_episode_steps: 500
max_grad_norm: 0.5
max_nodes: 500
mha_ff_dim_factor: 4
mha_num_attention_heads: 4
mha_num_attention_layers: 4
ppo_epochs: 10
rollout_steps: 2048
run_name: unified_spatial_ode_experiment
save_dir: ./checkpoints/unified_advanced
save_freq: 50
spatial_smoothness_coef: 0.05
splits_file: ./config/splits/combined_splits.yaml
success_distance: 1.0
time_step: 0.1
total_timesteps: 1000000
use_amp: true
use_counterfactuals: true
use_wandb: false
val_freq: 100
value_coef: 0.5
wandb_project: nomad-rl-unified-advanced
