batch_size: 32
buffer_size: 512
clip_ratio: 0.2
context_size: 3
curriculum_min_episodes: 20
curriculum_success_threshold: 0.6
curriculum_type: grid
curriculum_window_size: 20
dataset: ithor
device: cpu
distance_threshold: 1.0
encoding_size: 128
entropy_coef: 0.01
eval_episodes: 5
gamma: 0.99
goal_prob: 0.8
hidden_dim: 256
image_size:
- 224
- 224
lam: 0.95
learning_rate: 0.001
log_freq: 5
max_episode_steps: 200
max_grad_norm: 0.5
max_nodes: 100
ppo_epochs: 4
rollout_steps: 512
save_dir: ./checkpoints/test
save_freq: 20
splits_file: ./config/splits/ithor_splits.yaml
success_distance: 1.0
time_step: 0.1
total_timesteps: 10000
use_amp: false
use_counterfactuals: false
use_wandb: false
val_freq: 20
value_coef: 0.5
